spring:
  application:
    name: account-service
  profiles:
    active:
      - eureka-client
      - microservice
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 20
        max-interval: 15000
        initial-interval: 10000
      username: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}
  config:
    import: optional:configserver:${CONFIG_URI}
#  data:
#    redis:
#      password: from Config Server: Vault
#      host: from Config Server: Vault
#      port: from Config Server: Vault
#  datasource:
#    url: from Config Server: Vault
#    password: from Config Server: Vault
#    username: from Config Server: Vault

#auth:
#  jwt:
#    issuer: from Config Server: Git
#    access-expires-in: from Config Server: Git
#    refresh-expires-in: from Config Server: Git
#  keys:
#    access-token-public-key: from Config Server: Vault
#    access-token-private-key: from Config Server: Vault
#    refresh-token-public-key: from Config Server: Vault
#    refresh-token-private-key: from Config Server: Vault